{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.daniele21.localllm",
    "module": "android-binder-contract",
    "version": "0.1.0-alpha.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.daniele21.localllm",
          "module": "core-contracts",
          "version": {
            "requires": "0.1.0-alpha.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-binder-contract-0.1.0-alpha.5.aar",
          "url": "android-binder-contract-0.1.0-alpha.5.aar",
          "size": 275005,
          "sha512": "d153c504b378c0a6adc33ab7799a6cf6982aa0bc7a56785803668339c07623bd7eaf7c598c9537cefcfbfbbf1fe93231cf15b9c58cffdfb20c3dedbe8d0c1d73",
          "sha256": "0b1354520ea9fc2fe221182c2e0f8626cfa4671735a2b701b5d134a0b41f37ad",
          "sha1": "bb8cdcc7a4949cadf1d782e5858888df6567a183",
          "md5": "d0ca640c9e966b02c5f795beeb810f9e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "io.github.daniele21.localllm",
          "module": "core-contracts",
          "version": {
            "requires": "0.1.0-alpha.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-binder-contract-0.1.0-alpha.5.aar",
          "url": "android-binder-contract-0.1.0-alpha.5.aar",
          "size": 275005,
          "sha512": "d153c504b378c0a6adc33ab7799a6cf6982aa0bc7a56785803668339c07623bd7eaf7c598c9537cefcfbfbbf1fe93231cf15b9c58cffdfb20c3dedbe8d0c1d73",
          "sha256": "0b1354520ea9fc2fe221182c2e0f8626cfa4671735a2b701b5d134a0b41f37ad",
          "sha1": "bb8cdcc7a4949cadf1d782e5858888df6567a183",
          "md5": "d0ca640c9e966b02c5f795beeb810f9e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-binder-contract-0.1.0-alpha.5-sources.jar",
          "url": "android-binder-contract-0.1.0-alpha.5-sources.jar",
          "size": 51031,
          "sha512": "cd7da4ade432d1007cb8de27be9d7fa78a18787054c5463c8418c677031b3c814be84e8eea21aa10966394e858c99d14c2bf7c35e28356214984e6b3b2f11e11",
          "sha256": "a933f0d1e7c8d786a1b8a549445552b791457b9840f117d4143a843aa8e555db",
          "sha1": "af0df7860dc5b14f8931cdb9f31ca551e5845ce0",
          "md5": "56c926d4b578bd1f1edda67967022412"
        }
      ]
    }
  ]
}
