{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.daniele21.localllm",
    "module": "android-binder-contract",
    "version": "0.1.0-alpha.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.daniele21.localllm",
          "module": "core-contracts",
          "version": {
            "requires": "0.1.0-alpha.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-binder-contract-0.1.0-alpha.11.aar",
          "url": "android-binder-contract-0.1.0-alpha.11.aar",
          "size": 323893,
          "sha512": "9c24aab556f5e2f4e5929cac7ea1345dcc0c842948de334644d5599a99b40fbde9777eff11921c1f246561ca30d48f4fcb11cdf9f6da1769f30b69cc58abbbc2",
          "sha256": "f14e5d3af29c26dfd9e47f9c20a683b32b2b1e04dace6116f56cc0a21227ecb9",
          "sha1": "bbdc967078394e8396bc66fec368dedc3310d7a0",
          "md5": "c8294ebf8969414616528f438dd8fbc6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "io.github.daniele21.localllm",
          "module": "core-contracts",
          "version": {
            "requires": "0.1.0-alpha.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-binder-contract-0.1.0-alpha.11.aar",
          "url": "android-binder-contract-0.1.0-alpha.11.aar",
          "size": 323893,
          "sha512": "9c24aab556f5e2f4e5929cac7ea1345dcc0c842948de334644d5599a99b40fbde9777eff11921c1f246561ca30d48f4fcb11cdf9f6da1769f30b69cc58abbbc2",
          "sha256": "f14e5d3af29c26dfd9e47f9c20a683b32b2b1e04dace6116f56cc0a21227ecb9",
          "sha1": "bbdc967078394e8396bc66fec368dedc3310d7a0",
          "md5": "c8294ebf8969414616528f438dd8fbc6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-binder-contract-0.1.0-alpha.11-sources.jar",
          "url": "android-binder-contract-0.1.0-alpha.11-sources.jar",
          "size": 60611,
          "sha512": "66a278333669ac88c5dd09cdd0ee27e3fac8cda7e2191e1f0c8cdf190b4730a953d8fffec9b450cd9b0c2a0070607c9d681c598a039677ddde7c0052e1965533",
          "sha256": "a59dc8a07d3b8126c499caa006ccafa57f1d041be0d3f1b726e905a41bda1e67",
          "sha1": "6a2dec7b8940035785047a3113701aeb34c857f8",
          "md5": "63f7ee4f8751312fcd56fef3021e011c"
        }
      ]
    }
  ]
}
