{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.daniele21.localllm",
    "module": "android-binder-contract",
    "version": "0.1.0-alpha.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.daniele21.localllm",
          "module": "core-contracts",
          "version": {
            "requires": "0.1.0-alpha.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-binder-contract-0.1.0-alpha.7.aar",
          "url": "android-binder-contract-0.1.0-alpha.7.aar",
          "size": 296390,
          "sha512": "6126b8a3a811359e90ced67ffa70faa07589e2dc2eb23a9d9fd939dfe978cc9404dde6db64bbf21038ca81fe7a2cd85e1fe4c9a8ed6e59d603a83b9758e7414e",
          "sha256": "89a5c01ba46062e25479c8a23ab9ace394a6e0380f82ca34e8be1a754f244513",
          "sha1": "ede4adacc71dfdc1cdbb975c9f13fe3e03084180",
          "md5": "b642a16b495a5671fdbf707922b2d992"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "io.github.daniele21.localllm",
          "module": "core-contracts",
          "version": {
            "requires": "0.1.0-alpha.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-binder-contract-0.1.0-alpha.7.aar",
          "url": "android-binder-contract-0.1.0-alpha.7.aar",
          "size": 296390,
          "sha512": "6126b8a3a811359e90ced67ffa70faa07589e2dc2eb23a9d9fd939dfe978cc9404dde6db64bbf21038ca81fe7a2cd85e1fe4c9a8ed6e59d603a83b9758e7414e",
          "sha256": "89a5c01ba46062e25479c8a23ab9ace394a6e0380f82ca34e8be1a754f244513",
          "sha1": "ede4adacc71dfdc1cdbb975c9f13fe3e03084180",
          "md5": "b642a16b495a5671fdbf707922b2d992"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-binder-contract-0.1.0-alpha.7-sources.jar",
          "url": "android-binder-contract-0.1.0-alpha.7-sources.jar",
          "size": 54945,
          "sha512": "6b6990b60b979296c33e27f7025579d22618fba5635b1cf726a52cb9b748ee6e28fc70ac07933a7b7b7ef9e77ee14fa5f5a85ae62629fd9b574e2abf7f004844",
          "sha256": "90a631715f066c2da205430e3ea064636528825959fb885bd8cd0b0e7a7a7ecb",
          "sha1": "3d656b6853aba65d6e90c544a236435dfa174efa",
          "md5": "8be5935071e9c60d295b7b6c2c5da9b5"
        }
      ]
    }
  ]
}
