{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.daniele21.localllm",
    "module": "android-binder-contract",
    "version": "0.1.0-alpha.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.daniele21.localllm",
          "module": "core-contracts",
          "version": {
            "requires": "0.1.0-alpha.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-binder-contract-0.1.0-alpha.1.aar",
          "url": "android-binder-contract-0.1.0-alpha.1.aar",
          "size": 234132,
          "sha512": "3e84a6cda2881fd0489f145eb253daf1129bd7dfc12df5ad27f26510e1b25574b77798e03434aeac91a819dfd4b6326c777c9ed18684ae240aea45b88eb5bbd4",
          "sha256": "3333d48feb5553d64ca4fe810802efab6cb532126c6a7635ab4ced78ebc44d0f",
          "sha1": "105eb6b6fc18b531abe1113bf9beb4f86eeb6b0d",
          "md5": "7b7d045117060b08cefed522b92e97f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "io.github.daniele21.localllm",
          "module": "core-contracts",
          "version": {
            "requires": "0.1.0-alpha.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-binder-contract-0.1.0-alpha.1.aar",
          "url": "android-binder-contract-0.1.0-alpha.1.aar",
          "size": 234132,
          "sha512": "3e84a6cda2881fd0489f145eb253daf1129bd7dfc12df5ad27f26510e1b25574b77798e03434aeac91a819dfd4b6326c777c9ed18684ae240aea45b88eb5bbd4",
          "sha256": "3333d48feb5553d64ca4fe810802efab6cb532126c6a7635ab4ced78ebc44d0f",
          "sha1": "105eb6b6fc18b531abe1113bf9beb4f86eeb6b0d",
          "md5": "7b7d045117060b08cefed522b92e97f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-binder-contract-0.1.0-alpha.1-sources.jar",
          "url": "android-binder-contract-0.1.0-alpha.1-sources.jar",
          "size": 43995,
          "sha512": "26419fd032bf5e53fc24f3d369b8f7c00b3c4b8a3a2795dec793e8fd1ad81016fb011f5e43f44971e36c423bbf72c5edec58a5571eb7fcd795c9f32834abf272",
          "sha256": "ca485768c6b17268cd3d05fa076046e8e0360dad1aaae82f6ec7e29475ae53e3",
          "sha1": "dc514af324d4424358358136e44a3bd3fccee263",
          "md5": "c9bf6a4b990ee5c49fecc71ecd7ed8e7"
        }
      ]
    }
  ]
}
