{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.daniele21.localllm",
    "module": "android-binder-contract",
    "version": "0.1.0-alpha.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.daniele21.localllm",
          "module": "core-contracts",
          "version": {
            "requires": "0.1.0-alpha.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-binder-contract-0.1.0-alpha.8.aar",
          "url": "android-binder-contract-0.1.0-alpha.8.aar",
          "size": 323893,
          "sha512": "9c24aab556f5e2f4e5929cac7ea1345dcc0c842948de334644d5599a99b40fbde9777eff11921c1f246561ca30d48f4fcb11cdf9f6da1769f30b69cc58abbbc2",
          "sha256": "f14e5d3af29c26dfd9e47f9c20a683b32b2b1e04dace6116f56cc0a21227ecb9",
          "sha1": "bbdc967078394e8396bc66fec368dedc3310d7a0",
          "md5": "c8294ebf8969414616528f438dd8fbc6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "io.github.daniele21.localllm",
          "module": "core-contracts",
          "version": {
            "requires": "0.1.0-alpha.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-binder-contract-0.1.0-alpha.8.aar",
          "url": "android-binder-contract-0.1.0-alpha.8.aar",
          "size": 323893,
          "sha512": "9c24aab556f5e2f4e5929cac7ea1345dcc0c842948de334644d5599a99b40fbde9777eff11921c1f246561ca30d48f4fcb11cdf9f6da1769f30b69cc58abbbc2",
          "sha256": "f14e5d3af29c26dfd9e47f9c20a683b32b2b1e04dace6116f56cc0a21227ecb9",
          "sha1": "bbdc967078394e8396bc66fec368dedc3310d7a0",
          "md5": "c8294ebf8969414616528f438dd8fbc6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-binder-contract-0.1.0-alpha.8-sources.jar",
          "url": "android-binder-contract-0.1.0-alpha.8-sources.jar",
          "size": 60607,
          "sha512": "240175dc8560424184e4eecc8c31bf7453b3568e4caa71acd73edd3d5a02350b8632bc732f047013594d089a69c0c972a798db76cbfaeac82ec5b561c4b088de",
          "sha256": "a248407f9bc614399fdc7627c3e8681ca1f1e9beec6014edda069ed9e4f67213",
          "sha1": "0e5f840eb91b047b603abfa17de751e4744b7878",
          "md5": "e3039840154c009d1d880076713ef2ae"
        }
      ]
    }
  ]
}
